## 2.1. Data Manipulation
Tensors = n-dimensional arrays
* Tensor class in Pytorch and Tensorflow
* ndarray in Numpy and MXNet

In Pytorch, tensor class 
* supports autoDiff
* leverages GPUs (whereas Numpy only runs on CPUs)

### 2.1.1. Getting Started

In [1]:
import torch

In [2]:
# by default, new tensors are stored in main memory and designed for CPU-based computation

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# total num of elements
x.numel()

12

In [5]:
# a tensor has shape attribute, which is a tuple of lengths along each axis/dim 
x.shape

torch.Size([12])

In [6]:
x.reshape(3, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
x.reshape(3, 4).shape

torch.Size([3, 4])

In [8]:
# or, we can use -1 to automatically infer one component of shape
x.reshape(-1, 4) # No need to spell out .reshape(3, 4) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
# init
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn(3, 4)

tensor([[ 0.9485, -1.0332,  0.1052, -0.2226],
        [-1.3447,  0.3089, -0.1041,  0.6267],
        [-0.6337, -1.1708, -0.3728,  0.0455]])

### 2.1.2. Indexing, Slicing

In [11]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
# by default, if only one index or slice is specified for a n-D tensor, it is applied along axis 0

In [13]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [14]:
X[1:]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.3. Operations

In [16]:
# element-wise operations
torch.exp(X)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x+y, x-y, x*y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
# concat: along which axis to concat; along rows (axis 0) or columns (axis 1)
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  3.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [19]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X, X.sum(), X.sum(axis=0), X.sum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(66.),
 tensor([12., 15., 18., 21.]),
 tensor([ 6., 22., 38.]))

### 2.1.4 Broadcasting

### 2.1.5. Saving Memory

In [21]:
# Consider Y = X + Y
# a newly allocated memory is needed for X+Y, while the old Y is de-referenced

In [22]:
before = id(Y)
Y = X + Y
after = id(Y)
before, after

(2946437944160, 2946437937488)

In [23]:
# Better: update in place to reduce memory overhead
# Also, several references may point to the same tensor; should not refer to stale parameters
before = id(Y)
Y += X
after = id(Y)
before, after, before == after

(2946437937488, 2946437937488, True)

### 2.1.6 Conversion to Other Python Objects

In [24]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
# to get a scalar (1-d array in pytorch)
a = torch.tensor([1.2])
a, a.item()

(tensor([1.2000]), 1.2000000476837158)

## 2.2. Data Processing

### 2.2.1. Reading Dataset

In [26]:
import os

In [27]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [28]:
import pandas as pd

In [30]:
data = pd.read_csv(data_file)
data

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [32]:
# Notice how missing values are treated in the following two cells
inputs, targets = data.iloc[:,:2], data.iloc[:,2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1

In [33]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1

### 2.2.3. Conversion to the Tensor Format

In [34]:
X, y = torch.tensor(inputs.values), torch.tensor(targets.values)
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## 2.3. Linear Algebra

### 2.3.1. Scalars

### 2.3.2. Vectors
1-d array

### 2.3.3. Matrices

In [36]:
A = torch.arange(6).reshape(3,-1)
A, A.T

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [37]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A, A.T, A == A.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

### 2.3.4. Tensors
* An image is a 3-d tensor: axes = height, width, channel
* A video is a 4-d tensor: axes = time, height, width, channel

In [39]:
torch.arange(24).reshape(3, 4, -1)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

### 2.3.5. Tensor operations

In [41]:
# Element-wise product of two matrices is called the Hadamard product
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, B, A*B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]))

### 2.3.6. Reduction
By default, .sum() reduces a tensor along all of its axes.

To sum over along the row, specify axis=0; to over column, axis=1

In [43]:
A, A.shape, A.sum()

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor(15.))

In [46]:
# sums of columns, sums of rows
A.sum(axis=0), A.sum(axis=0).shape, A.sum(axis=1), A.sum(axis=1).shape

(tensor([3., 5., 7.]), torch.Size([3]), tensor([ 3., 12.]), torch.Size([2]))

In [48]:
# likewise for .mean()
A, A.mean(), A.mean(axis=0), A.mean(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(2.5000),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([1., 4.]))

### 2.3.7. Non-Reduction Sum
Sometimes, it can be useful to keep the number of axes unchanged

In [50]:
sum_A = A.sum(axis=1, keepdims=True)
A, A.shape, sum_A, sum_A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [52]:
# Since sum_A keeps its two axes, we can use it to "normalize" each row of A (so each row of A add up to 1)
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [53]:
# By design, .cumsum() keeps dim
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.]])

### 2.3.8. Dot Products

In [71]:
x = torch.tensor([1,2,3], dtype=torch.float32)

In [72]:
y = torch.ones_like(x)
y

tensor([1., 1., 1.])

In [73]:
x, y, torch.dot(x, y), torch.sum(x*y)

(tensor([1., 2., 3.]), tensor([1., 1., 1.]), tensor(6.), tensor(6.))

In [74]:
xhat = x / (torch.dot(x, x))**0.5
(torch.dot(xhat, xhat))**0.5

tensor(1.0000)

### 2.3.9. Matrix-Vector Products
(Ax)[i] = torch.dot(A[i,:], x)

In [75]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [76]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 8., 26.]), tensor([ 8., 26.]))

### 2.3.10. Matrix-Matrix Products

In [79]:
B = torch.ones(3, 4)
A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [82]:
torch.mm(A, B), A@B # Should not be confused with Hadamard Product A*B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### 2.3.11. Norms
A notion about the size, magnitude, not its dimensionality

A norm is a function from a vector space to a scalar such that
* norm(X) > 0 for all X != 0
* norm(aX) = abs(a)*norm(X)
* norm(X + Y) <= norm(X) + norm(Y)

Why this concept is useful?
* In deep learning, we are solving optimization problems: maximize the probability assigned to observed data, maximize the revenue associated with a recommender, minimize the distance between predictions and ground-truth observations, minimize distance(same person's photos) while maximize distance(diff persons' photos)
* These distances (often the objectives of DL algos) are often expressed as norms.

In [93]:
# l1 norm
x = torch.tensor([[3, 4]], dtype=torch.float32)
x, torch.norm(x, p=1), torch.sum(torch.abs(x))

(tensor([[3., 4.]]), tensor(7.), tensor(7.))

In [95]:
# l2 norm
x, torch.norm(x, p=2), (torch.sum(torch.abs(x**2)))**(1/2)

(tensor([[3., 4.]]), tensor(5.), tensor(5.))

In [96]:
def lp_norm(vec, p):
    norm = torch.sum(torch.abs(x**p))
    norm = norm**(1/p)
    return norm

In [97]:
lp_norm(x, 1), lp_norm(x, 2)

(tensor(7.), tensor(5.))